
export const API_DATE_TIME = 'yyyy-MM-dd HH:mm:ss xxx'

export const categories = [
  'General',
  'Art Classes / Exhibitions',
  'Author Q&A Events',
  'Barista or Coffee Brewing Workshops',
  'Book Clubs / Author Talks',
  'Career Coaching Sessions',
  'Comedy Shows',
  'Conferences & Summits',
  'Cooking or Mixology Classes',
  'Cultural Talks / Heritage Tours',
  'Dance Classes (Salsa, Hip-Hop, etc.)',
  'Digital Marketing Workshops',
  'DIY Home Improvement Classes',
  'Esports Tournaments / Gaming Events',
  'Film Watch Parties + Discussion',
  'Fitness Classes (Zumba, HIIT, Dance)',
  'Fun Runs / Charity Walks',
  'Game Nights / RPG Sessions',
  'Gardening or Urban Farming Classes',
  'Language Classes',
  'Leadership or Public Speaking Workshops',
  'Life Coaching Webinars',
  'Live Concerts / DJ Sets',
  'Magic or Illusion Shows',
  'Masterclasses (film, writing, business)',
  'Mindfulness & Stress Relief Sessions',
  'Networking Mixers / Speed Networking',
  'Nutrition & Lifestyle Coaching',
  'Open Mic Nights',
  'Other',
  'Panel Discussions / Fireside Chats',
  'Parenting Workshops',
  'Personal Branding Workshops',
  'Pet Training or Care Classes',
  'Photography Workshops',
  'Podcasting Workshops',
  'Product Launch Events',
  'Professional Certification Bootcamps',
  'Real Estate Investing Seminars',
  'Resume & Interview Skills Sessions',
  'Small Business / Startup Clinics',
  'Social Media Strategy Courses',
  'Spoken Word / Poetry Nights',
  'Tech Webinars (coding, AI, marketing)',
  'Theater Acting or Voice Workshops',
  'Trivia Nights',
  'UX/UI Design Courses',
  'Virtual Reality (VR) Experiences',
  'Webinars / Expert Talks',
  'Wellness Retreats',
  'Workshops (Art, Craft, Music, DIY)',
  'Writing Circles / Poetry Workshops',
  'Yoga / Meditation Sessions',
]