version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:645972258043:task-definition/EBSTaskDefFamily:1"
        LoadBalancerInfo:
          ContainerName: "ebs-api"
          ContainerPort: 80