# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build mobile application

on:
  push:
    branches:
      - mobile

jobs:
  mobile_debug_build:
    name: Mobile app debug build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - uses: w9jds/setup-firebase@main
        with:
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          tools-version: 11.9.0
          project_path: apps/mobile/
      - run: firebase login
      - run: firebase deploy --only hosting
      - run: firebase deploy --only functions
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.3
      - run: flutter --version
      - run: cd apps/mobile/
      - run: pwd
      - run: ls
      - run: |
          cd apps/mobile/
          touch .env
          echo ${{ vars.API_HOST }} >> .env
          echo ${{ secrets.API_SECRET }} >> .env
          flutter pub get
          # flutter test
          flutter build apk
          # flutter build aab